### ISSUE TITLE
How to remove Background from live steaming?

### ISSUE THREAD

**Issue by hemant-novotrax** [pedroSG94/RootEncoder#1047]
Hello 
Please help ,
I want to remove background of object from live streaming .can i remove background using filters?

**Comment by pedroSG94** [comment]
Hello,

For now, the only similar filter added by default is chroma filter. With this filter you can replace a chroma (green background) with an image.

For example. Reproduce this video on a PC:
https://www.youtube.com/watch?v=aWyge8HfF4Q&list=PLTH1W-kYjBQPMw0T2Oa9aNlWlPzAkYQmM
Using OpenGl RTMP example, enable chroma filter and focus the camera on the video and you will see on the preview that the green background is replaced by an image.

**Comment by hemant-novotrax** [comment]
Hello padro,

First of all thanks for given us to wonderful Streaming library . This this helpful to us.

You are talking about chroma filter but I am telling about deeplabv3 (Please see this :- ***@***.***/image-segmentation-for-android-smart-background-replacement-with-fritz-a09d8b0592a4) .

I am just want to know that can we implement this effect in rtmp streaming. If yes, please respond me.

Thanks you

***@***.***/image-segmentation-for-android-smart-background-replacement-with-fritz-a09d8b0592a4>
Image Segmentation for Android — Smart Background Replacement with Fritz AI | by Eric Hsiao | ***@***.***/image-segmentation-for-android-smart-background-replacement-with-fritz-a09d8b0592a4>
All of our Vision APIs follow a similar format in order to run prediction on an image. This is a high-level overview but if you’d like more details, you can take a look at our Image Segmentation ...
medium.com

________________________________

**Comment by pedroSG94** [comment]
Hello,

I can't see your link but I think that you mean this:
https://medium.com/@hsiaoer/image-segmentation-for-android-smart-background-replacement-with-fritz-a09d8b0592a4

In this case, It can't be implemented because it is using a bitmap to work.
Implement it to work on fly is not possible because it take too much time to process and the result could be less than 10fps using good devices in 1080p.
Also, I'm not sure if that library provide you a way to know where you need to replace a pixel.
It is designed to work as post process image filter not a real time filter.

**Comment by hemant-novotrax** [comment]
Hello,
I want help from you .
After change activity Can I send continued frame send to server in rtmp ?
________________________________

**Comment by pedroSG94** [comment]
Yes, you can do it like in this example:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/tree/master/app/src/main/java/com/pedro/rtpstreamer/backgroundexample
