### ISSUE TITLE
Can I read QR code through your library?

### ISSUE THREAD

**Issue by ArqinT** [pedroSG94/RootEncoder#1053]
Can I read QR code through your library?

**Comment by pedroSG94** [comment]
No, this library is used only for streaming.

**Comment by ArqinT** [comment]
How can i combine streaming from your library with reading qr code?

**Comment by pedroSG94** [comment]
You can try this:
- Take a photo using this method:
```java
rtmpCamera1.getGlInterface().takePhoto(new TakePhotoCallback() {
      @Override
      public void onTakePhoto(Bitmap bitmap) {
        //read QR here
      }
    });
```
- Using Zxing library, you can read the bitmap generated to detect QR code:
https://github.com/zxing/zxing
https://stackoverflow.com/a/39953598

**Comment by ArqinT** [comment]
Thx a lot!
But I need to capture QR without any click and buttons. How can I set any detectors to camera?

For example the com.google.android.gms.vision.CameraSource  has Builder class. I can provide to Builder my own Detector.

```
barcodeDetector = BarcodeDetector.Builder(this)
            .setBarcodeFormats(Barcode.ALL_FORMATS)
            .build()
        cameraSource = CameraSource.Builder(this, barcodeDetector)
            .setRequestedPreviewSize(1920, 1080)
            .setAutoFocusEnabled(true)
            .build()
```

**Comment by pedroSG94** [comment]
This library is not designed to support it. You only can do it as explained above without modifications.
If you still want do it you will need modify library a bit (It is easy to do)
Since Vision API library is deprecated you should use this library:
https://developers.google.com/ml-kit/vision/barcode-scanning/android
In this case you must use camera2 and add to this class a callback to obtain frames provided by camera2:
- Go to this class: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/encoder/src/main/java/com/pedro/encoder/input/video/Camera2ApiManager.java
- Add an ImageReader to camera2 as explained here:  https://stackoverflow.com/questions/50576912/capturing-image-using-camera2-api
- Use that callback to detect QR using bytebuffer or bitmap: 
https://developers.google.com/ml-kit/vision/barcode-scanning/android#using-a-bitmap
https://developers.google.com/ml-kit/vision/barcode-scanning/android#using-a-bytebuffer-or-bytearray
- How to convert Image to bitmap or bytebuffer:https://stackoverflow.com/a/28843224

**Comment by pedroSG94** [comment]
Closing as inactive.
