### ISSUE TITLE
trsp Screen recording problem

### ISSUE THREAD

**Issue by tiantianqin001** [pedroSG94/RootEncoder#1064]
I am using the rtsp protocol to push the stream and found that the player opening delay is about 10 seconds. I found that the queue of the start() method of the RtspSender class has a delay of 1 second when fetching data. Is this the reason for the delay?
![0004E6C0-8AC7-40C2-95AD-8296B5E3CDB0](https://user-images.githubusercontent.com/50287417/155747904-3f60d005-9d21-487b-82f2-e0f882e49683.png)

**Comment by pedroSG94** [comment]
No, it is not related.
That means wait only if you haven't frames in queue. You can write a logcat before and after that line to know it but it is time time to wait until a video/audio frame is produced.

In your case the delay could be:
- Device speed: This is the library delay from the frame is produced (camera or microphone generate a frame) to the frame is send to server. Normally around 1s and improve depend of device. (tested time ago using logs)
- Internet connection: Delay from the device send the packet to server receive that packet or server send to player and player  receive it.
- Server delay: Time used by server to process the frame until it is send to player. In this step included change protocol (for example from RTSP to HLS), resolution transcoing (use a different resolution send from device to allow reproduce in multiple resolutions). In most of cases the delay could be produced here.
- Player delay: Delay from the player receive the packet to player reproduce the packet. Normally all players have buffers and it is the reason about delay in most of cases.

My sugestion is use a server with low delay in local network and use a player with low delay like ffplay without change the original protocol (send and reproduce in RTSP). In my tests, I get around 2s of delay using a decent device like Oneplus 7T.
I have tests with images here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/969

**Comment by tiantianqin001** [comment]
The streaming media server I use is a local LAN service. I use the Windows computer FFmpeg to push the streaming command ffmpeg -f gdigrab -framerate 15 -i desktop -f dshow -b:v 2000k -bufsize 0 -minrate 4000k -maxrate 6000k -vf scale= 1920:1080 -c:v libx264 -preset:v ultrafast -tune:v zerolatency -pix_fmt yuv420p -keyint_min 300 -g 300 -bf 0 -sc_threshold 0 -f rtsp -rtsp_transport tcp rtsp://192.168.11.37:555/live /tiantianqin is using ffplay -i rtsp://192.168.11.37:555/live/tiantianqin to play with a 1 second delay. I feel (tested many times), using your open source library, I read the source code for 2 days and found the encoded data Put it in a blocking queue set, open a thread and log the data set of this blocking queue. It is found that the queue does not have too much size(). The playback delay of ffpay on the android side is now more than 7 seconds. I can't find what's wrong, I hope to get your help, mainly because the windows side uses ffmpeg to push the stream, and the ffplay playback delay is about 1 second, I can't say it's a server problem.

**Comment by tiantianqin001** [comment]
The delay I am talking about is that the delay time is about 7 seconds when it is just turned on. Once it is played with ffplay, the screen delay is about 2 seconds. The optimization I am talking about is why the delay time is so long when it is just turned on. I need to get your help

**Comment by tiantianqin001** [comment]
The delay I am talking about is when the android pad starts to record the screen and push the stream. It takes a delay of more than 7 seconds to play the screen with ffplay. Once the screen is seen, the delay is about 2 seconds. After such a long time, can I see the screen in 2 to 3 seconds, I need your help

**Comment by tiantianqin001** [comment]
The streaming server I am using is a local lan streaming service. I use Windows computer FFmpeg push stream command ffmpeg -f gdigrab -framerate 15 -i desktop -f dshow -b:v 2000k -bufsize 0 -minrate 4000k -maxrate 6000k -vf scale= 1920:1080 -c:v libx264 -preset: v ultrafast -tune:v zerolatency -pix_fmt yuv420p -keyint_min 300 -g 300 -bf 0 -sc_threshold 0 -f rtsp -rtsp_transport tcp rtsp://192.168.11.37:555/live /tianqin using ffplay -i rtsp:// 192.168.11.37:555/live/tiantianqin playback is delayed by 1 second. Feeling (tested many times), use your open source library, read the source code for 2 days, and find that the encoded data is placed in a blocking queue collection, open a thread, and record the data collection of this blocking queue. Found that the queue doesn't have too much size(). ffpay can see that the playback delay of the screen on the android side is now more than 7 seconds. I don't know the reason. Once I see the screen, the delay is about 2 seconds. I hope I can get your help. It is mainly because the windows side uses ffmpeg to push the stream, and the ffplay playback delays about 1 second. It cannot be said that it is a server problem. .

**Comment by pedroSG94** [comment]
If you are using RtspDisplay class. MediaProjection API has delay and I have no way to solve this.
Try to use RtspCamera to know the delay difference.

You have examples here using this server and ffplay:
https://github.com/EasyDarwin/EasyDarwin
Device used: Android studio emulator Pixel 4a API 30 (x86)

Using OpenGl RTSP example:
Timer added using TextObjectFilterRender filter. It is basically milliseconds since filter started.

ffplay command:
```
ffplay rtsp://192.168.1.132/live/pedro
```
![camera1delay](https://user-images.githubusercontent.com/17556876/156139488-76a1c17f-b71e-41d0-9c73-9478def9133d.png)
Delay: 3,8s 
ffplay command:
```
ffplay -fflags nobuffer rtsp://192.168.1.132/live/pedro
```
![camera1delaynobuffer](https://user-images.githubusercontent.com/17556876/156139679-0df83818-4ae7-4cc3-bfdf-47603db9d407.png)

Delay: 0,3s (it is the same stream the only difference is the ffplay command so the problem seems ffplay buffer)

Using Display RTSP example:
I used Clock app to show a timer.

ffplay command:
```
ffplay rtsp://192.168.1.132/live/pedro
```
![screendelay](https://user-images.githubusercontent.com/17556876/156140431-199e27b8-3b53-42f1-af6b-1d0085bb3114.png)
Delay: 5,2s
ffplay command:
```
ffplay -fflags nobuffer rtsp://192.168.1.132/live/pedro
```
![screendelaynobuffer](https://user-images.githubusercontent.com/17556876/156140447-b4e9e40b-ad83-4dee-8567-e3b3dd3f8909.png)
Delay: 3,3s

As you can see the library using Camera1 has delay close to 0 if you configure player with no buffer but using display the delay increase to 3s (it is the mentioned delay of MediaProjection API).

**Comment by tiantianqin001** [comment]
OK ，Thank you very much for your answer
