### ISSUE TITLE
RTP over UDP streaming

### ISSUE THREAD

**Issue by 1goresha** [pedroSG94/RootEncoder#1077]
Can i use your library for clear RTP(not RTSP) over UDP streaming? And how? Can you direct me to the answer, please?
I want to achieve high speed by sacrificing guaranteed packet delivery.
It is very interisting for me.
Thank you in advance.

**Comment by 1goresha** [comment]
I can't understand why the p2p network delay is 3 seconds, in your library RTP over UDP(default) is used, is not it?

**Comment by pedroSG94** [comment]
Hello,

rtsp module use TCP by default.
The delay is normally produced in player side. You have an example that you can reproduce in local network here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/1064#issuecomment-1055206908
If you are using RTSP-Server project the case is similar try using ffplay with -fflags nobuffer.

**Comment by 1goresha** [comment]
I tested RTSP-Server in wifi local(wifi hotspot from android device).
RTSP-Server is on android device and ffmpeg is on windows(10), i used ffplay and ffplay -fflags nobuffer, difference is 2-3 seconds, really huge.
It means that i need to configure player side for low latency?
And, can i change protocol in your library in rtsp module to UDP? Is it possible?

**Comment by pedroSG94** [comment]
Hello,

with rtsp module you can change TCP to UDP using this line:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/app/src/main/java/com/pedro/rtpstreamer/customexample/RtspActivity.java#L235

In case of RTSP-Server the player will decide if use TCP or UDP (I support both). You can read it in logcat:
https://github.com/pedroSG94/RTSP-Server/blob/master/rtspserver/src/main/java/com/pedro/rtspserver/ServerClient.kt#L57
Check the logcat and you can know it. It is received in PLAY command from player side.

You will need find the way to force one protocol in your player.

**Comment by 1goresha** [comment]
Ok, i see.
My player uses UDP.
Thank you for answer.
But anyway, is it possible to use your library for RTP streaming (audio and video) without RTSP.
I am a new in streaming protocols and just started to study your library, i apologize in advance for some may be obvious questions.

**Comment by 1goresha** [comment]
Oh, i see, but is it possible to implement this protocol in your library?
May be you have some ideas or recomendations for this?

**Comment by pedroSG94** [comment]
This is possible because you can create a new module with that protocol and add it to project without modify encoder module.
In this case rtp in ffmpeg is a stream of rtp packets directly without add previous rtsp negotiation with server but I have multiple question about it.
- How to different video and audio?
In rtsp you are using headers to send 2 tracks in tcp and one port per track in udp according with rtsp negotiation.
- Do you send any previous info before start send rtp packets?
If you get rtsp module and remove rtsp negotiation in RtspClient class you are doing rtp of ffmpeg but I need resolve that questions first to modify it.

Anyway this protocol is not used normally and you haven't so much players that support it. For that reason, if it require so much time it isn't worth to develop.

**Comment by 1goresha** [comment]
If you could answer these questions, it would be great! 👍 
i think it will be usefull for many!

**Comment by pedroSG94** [comment]
I will investigate a bit about it but for now I'm developing other feature so I don't know when I will do it.
Also, it isn't really interested since not so much server/players support it

**Comment by pedroSG94** [comment]
I have no plan to do it for now. I can change my idea if more users needed it
Closing as inactive.
