### ISSUE TITLE
Consistent FrameDrops even in Strong Network

### ISSUE THREAD

**Issue by pushpendra-ncompass** [pedroSG94/RootEncoder#1099]
Hey there @pedroSG94 ,
While using the stream for on a good network, the stream is running fine, but after sometimes(about 20 - 30 mins), there is consistent frame drops in the stream, even if the network is good with no congestion, the frames are dropping. I researched about it, but didn't find anything useful.

I want to ask is there a way so that the frames do not drop consistently after few mins

[Image Url 1](https://imgur.com/OCPgR7m)
[Image Url 2](https://i.imgur.com/2S0aJIq.png)

Thanks you again for the library.

**Comment by pedroSG94** [comment]
Hello,

I recommend you test first in a local server to discard internet problems.

After that, you can check in logs of the library to know if you are losing frames. The logs should be similar to:
```
Video frame discarded
Audio frame discarded
```
If you have this logs, this means that you are producing frames faster than send it and normally it is because of internet stability problems maybe in server, in device or any server of the route.
If you haven't this logs, maybe you are receiving frames too late and server discard it automatically and it is again an internet connection problem because it take so much time to send sometimes. This is normally produced if you have an micro internet lag spike producing send fews packet too late and dropping all in server side.
