### ISSUE TITLE
Streaming TextureView

### ISSUE THREAD

**Issue by hogantan** [pedroSG94/RootEncoder#1104]
Is it possible to stream a specific TextureView/SurfaceView rather than streaming my entire display? 

I am not sure where to start. Can someone point me in some direction? Thanks!

**Comment by pedroSG94** [comment]
Hello,

Without modify the library it is not posible.
I'm not sure if it is working but you can stream an android view using AndroidViewFilterRender (You can stream display and set this filter with full size using setSize(100,100)). I recommend you test it but maybe it is not working because SurfaceView and TextureView are specials views and get frames using canvas not always work for it.

If you want stream SurfaceView or TextureView you need a proper way to extract frames from it and render another Surface (VideoEncoder inputSurface) with that frames but depend of the way you are doing it it is not always possible.
