### ISSUE TITLE
RTSP to RTMP with some processing

### ISSUE THREAD

**Issue by jnebrera** [pedroSG94/RootEncoder#1208]
Hello Pedro,
I would like to know if this project would be possible based on your library:
1) Connect to 1 (or many) RTSP video source
2) Process each frame for AI related stuff (People detection)
3) Crop the original video source to a final HD frame
4) Overlay external HTML content
5) Stream to the internet using RTMP(s)
Thank you very much

**Comment by pedroSG94** [comment]
Step 1 is not possible because you need a player and this library only work as a pusher
Step 2 could be possible but really difficult to handle because you need take a frame each X time (you can do it using takePhoto method) and proccess it using other library (it is maybe the problem because you need use openCV and I'm not sure about the performance. The library is not thinking to do it since image proccesing is working with openGL, take frames constantly is a bad idea (the performance for it is slow).
Steps 3, 4 and 5 is possible using filters.

I think it is not your library since step 1 is not possible and step 2 could result in a bad performance.
