### ISSUE TITLE
I want to modify payloadType

### ISSUE THREAD

**Issue by sunbinkang** [pedroSG94/RootEncoder#1215]
Hi pedroSG94，Excuse me. current audio payloadType is 97，our server say: I need to modify this num to 104,  I modify this code(RtpConstants.payloadType + RtpConstants.trackAudio + 7) to test,  I use VLC player to Play , but the player has no sound. payloadType = 97, the player has sound. so I need to modify where？Thanks pedroSG94。
I use RTSP-Server demo implementation the rtmp-rtsp-stream-client-java library，but I modify audio aac payloadType to 104 in rtmp-rtsp-stream-client-java library。

**Comment by sunbinkang** [comment]
Hi pedroSG94, I may be solved it. I change this value （var trackAudio = 8），so video payloadType = 96 + 8. just now, I test this rtsp stream has sound. but I dot know why now. haha

**Comment by pedroSG94** [comment]
Hello,

The audio/video payload is calculated like this:
base payloadType (96) + audio/video track

The audio payload is normally 97 (track 1) and the video payload is 96 (track 0). If you disable video or audio the payload is always 96 because you only have one track.

Since 96 is the payloadType used for this type of media content. This means that you server expect audio in the track number 8 as you did. You can send all tracks that you need not only 2 or use any number. For example you can send 2 tracks of video with different resolutions and reproduce any of them in the player side (it is not developed by me but it is supported in rtsp protocol)

I only can tell you that it is really weird because a server normally accept any track used (it is the reason because you normally start with track 0 and 1). Maybe the problem is that your track number 1-7 is already in use. I don't know.
