### ISSUE TITLE
SpsPps is Null when Using Camera2 in ExampleCode

### ISSUE THREAD

**Issue by DoleXio** [pedroSG94/RootEncoder#1218]
Why running the [rtmp-rtsp-stream-client-java], I always meet "sps or pps is null" when try to run TextureModeRTSP. Other RTSP by  Camera1(Custom, Default,OpenGI ) or RTMP is OK. 
wish to get help， thanks

ref：
Android Studio Dolphin | 2021.3.1 Patch 1
ZLMediaKit

**Comment by pedroSG94** [comment]
Hello,
I recommend you use camera2 with OpenGlView or LightOpenGlView if you don't need filters. TextureView and SurfaceView with camera2 are deprecated because it is not customizable and produce problems since you need set 2 surfaces to camera2 API (encoder and preview).
If you still need it. Can you try force use software video encoder?:
```java
rtmpCamera2.setForce(CodecUtil.Force.SOFTWARE, CodecUtil.Force.FIRST_COMPATIBLE_FOUND);
```

**Comment by DoleXio** [comment]
thanks
