### ISSUE TITLE
(texturemodeexample) rtspCamera2 and texture_mode video recording not working

### ISSUE THREAD

**Issue by alexz006** [pedroSG94/RootEncoder#1266]
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/f1d2fc6fba5ebba98e2be6bb5360d81103106816/app/src/main/java/com/pedro/rtpstreamer/texturemodeexample/TextureModeRtspActivity.java#L78C23-L78C23

```java
// private RtmpCamera2 rtmpCamera2; // it doesn't work
private RtmpCamera1 rtmpCamera2; // it works
@Override
  protected void onCreate(Bundle savedInstanceState) {
  // rtmpCamera2 = new RtmpCamera2(textureView, this); // it doesn't work
  rtmpCamera2 = new RtmpCamera1(textureView, this); // it works
```

**Comment by pedroSG94** [comment]
Hello,

Actually SurfaceView and TextureView are deprecated with Camera2 because it send 2 surfaces to camera and somes devices can't do it:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpCamera2.java#L56
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtplibrary/src/main/java/com/pedro/rtplibrary/rtmp/RtmpCamera2.java#L67
The recommended way to use the library is with OpenGlView or LightOpenGlView if you dont want filters.
SurfaceView and TextureView with camera1 is mainly if you want support devices with API 16 and 17 because this way is really bad in performance since you are manipulating buffers instead of do it with opengl

**Comment by alexz006** [comment]
I need the camera to be able to work in the background, and this can only be done using TextureView (or not only?)

I would also like to record video in mkv or webm format, so that in case of unforeseen circumstances, the previously recorded video could be viewed. Please tell me how can this be done?

**Comment by pedroSG94** [comment]
About video in mkv or webm. The library only support record on MP4
WEBM use vp8/vp9/av1 video and opus audio codecs not supported by this library so you can't record in that format (this library support H264/H265 video and AAC audio)
MKV is not supported by Android natively

**Comment by alexz006** [comment]
Thank you for your responses!
Are you planning to add WEBM format?

**Comment by pedroSG94** [comment]
I'm not sure.

Currently I'm developing SRT protocol that could take time. Also, add opus and VP8/9 codecs is not really worth since only RTSP support it.
It is not planned in a next future at least
