### ISSUE TITLE
How can I send Metadata to server with each frame?

### ISSUE THREAD

**Issue by hamzanaeemcowlar** [pedroSG94/RootEncoder#1293]
Hello @pedroSG94,

Is there any way to send metadata to the server with each and every frame? I would like to send the timestamp with each frame. I looked at a method that could send the metadata on connection, but is it possible to send it with each frame?

Thanks and Regards

**Comment by pedroSG94** [comment]
Hello,

I assume that you want do it with RTMP.
Timestamp is already send with each frame in the rtmp message header:
https://github.com/pedroSG94/RootEncoder/blob/master/rtmp/src/main/java/com/pedro/rtmp/rtmp/message/Video.kt#L31

If you want send other info you will need modify the library to adjust to your server since rtmp don't have a standard way to do it.

**Comment by pedroSG94** [comment]
Closing as inactive.
