### ISSUE TITLE
RtmpFromFile

### ISSUE THREAD

**Issue by Munccccc** [pedroSG94/RootEncoder#1301]
Hi, when using RtmpFile, If I don't use file synthesis，how do I push multiple files in a row without breaking the server connection.

**Comment by pedroSG94** [comment]
Hello,

Currently it is not possible. The only way is join all files in one before start stream.
Develop this feature is very complex because each file could contain a different codec, format, resolution, audio sample, etc.

I could add this feature if all file are identical but I still need check all and show an error if necessary.
I will add it to the possible features but don't expect it soon.

**Comment by Munccccc** [comment]
Yes, the internal codec and format of the file are the same.

Right now I have to disconnect and reprogram the codec every time for it to work.

**Comment by pedroSG94** [comment]
Maybe you can try use a library to merge videos and then stream. I found this on google but I don't know if this could work:
https://stackoverflow.com/questions/68035473/merging-two-video-by-using-mp4parser-display-video-as-upside-down

**Comment by Munccccc** [comment]
> Maybe you can try use a library to merge videos and then stream. I found this on google but I don't know if this could work: https://stackoverflow.com/questions/68035473/merging-two-video-by-using-mp4parser-display-video-as-upside-down

Thank you, but I don't want to use the way of video synthesis at present.

**Comment by Munccccc** [comment]
Hi,I have modified your BaseDecoder to support fileList passing.
