### ISSUE TITLE
srtStreaming Portait not working as expected

### ISSUE THREAD

**Issue by ToysoftInc** [pedroSG94/RootEncoder#1306]
**Describe the bug**
When streaming portrait to the server I notice some differences between other apps.
See picture.  When using MiniServer the preview still not working as expected.
But if I send the activity to landscape then the preview is working fine.  Does not matter which decoder I select from the server it is still not displaying correctly.

Also in the screen shot the one feed is from another app and the second feed is from the Root sample app.
I just changed the resolution.  Notice the width and height are different.

I'm using the Larix Broadcaster android app to test with Root lib

**To Reproduce**
1. run the miniserver
2. stream 

**Expected behavior**
Preview for Portrait should display properly

**Additional context**
Also in the miniServer it can stream to 3rd apps like vlc.  When I try with vlc and using the Root sample vlc can not play the feed but with other app I was able to play the feed.

![miniserver_oct13](https://github.com/pedroSG94/RootEncoder/assets/18074554/4931400e-f70f-467d-8a6e-aba375ea7d28)

**Comment by pedroSG94** [comment]
Hello,

The preview is an error in the SRTMiniserver player. I can reproduce it using larix app as you did. The problem is related with vertical resolution. In my case I can solve it using hardware decoder. I share you a video here:
[2023-10-14 00-43-43.zip](https://github.com/pedroSG94/RootEncoder/files/12900169/2023-10-14.00-43-43.zip)

Of course you can use my library in landscape or even rotate in realtime like larix.
About reproduce the stream with VLC or OBS. I can't do it. How are you doing it?
I tried using this guide:
https://srtminiserver.com/help/play_srt_from_server.html

**Comment by pedroSG94** [comment]
Closing as inactive.
