### ISSUE TITLE
Move methods from subclasses to Camera2Base

### ISSUE THREAD

**Issue by Ernovation** [pedroSG94/RootEncoder#1319]
The subclasses of `com.pedro.library.base.Camera2Base` all have a method `getStreamClient()`, but they all have different return types, depending of the protocol: RTSP, RTMP or SRT. But these return types all extend `StreamBaseClient`. If the return type of `getStreamClient()` would be `StreamBaseClient`, the method could be moved to `Camera2Base`.
This would make it easier to use a `Camera2Base` and for example check for congestion. Now I have to do this:

```
val congestion =  when (camera) {
    is RtmpCamera2 -> {
        camera.streamClient.hasCongestion(50.0f)
    }
    is RtspCamera2 -> {
        camera.streamClient.hasCongestion(50.0f)
    }
    is SrtCamera2 -> {
        camera.streamClient.hasCongestion(50.0f)
    }
    else -> {
        false
    }
}
```
If getStreamClient() would return StreamBaseClient, I could just do:
`
val congestion = camera.streamClient.hasCongestion(50.0f)
`

The same is true for the other public method of e.g. RtmpCamera2: `public void setVideoCodec(VideoCodec videoCodec)`, where even every <protocol>Camera2 has a different `VideoCodec` class, with the same values.

Moving these methods to Camera2Base would make the use of these two public methods more elegant.

**Comment by pedroSG94** [comment]
Hello,

Solved here:
https://github.com/pedroSG94/RootEncoder/commit/59e50539c29b73d5b02e7d8159661a93716ca597

But it is only usable for commons methods. If you want to use other methods like setWriteChunkSize of RTMP you will need cast to RtmpCamera2

**Comment by pedroSG94** [comment]
setVideoCodec method moved to base in all classes:
https://github.com/pedroSG94/RootEncoder/commit/0d35e08fa854c4310a8c707c7d87d8c2a5e41b87

**Comment by Ernovation** [comment]
Thanks, Pedro! That was fast!
I have been thinking a bit more about the implementation and I think what would be even better is to have a generic Camera2 class, independent of protocol. In that class, only when you start streaming, the appropriate streaming client is selected, based on the URL. 
That way you could already have a preview, before you know how you will stream it.
Now the protocol to use is hardcoded by the user (developer, i.e. me) of the library by hardcoding for example the  RtmpCamera2 class. But a generic Camera2 class could be used by all protocols, and only have a different streaming client when streaming.
I think that this would need some refactoring, because also the ConnectChecker classes are different for all protocols, even though they have the same methods.
What do you think about this idea? I could try to implement it later this week, when I have time. Or do you see problems with this approach? I think if you still want to call some protocol specific method, you could get the stream client from the camera object, and cast the stream client object to some protocol specific class.

**Comment by pedroSG94** [comment]
Hello,

Yes, your idea is good but at same time we need to find a way to handle with specific rtmp, rtsp and srt methods like setWriteChunk of rtmp or setProtocol of rtsp provided by RtmpStreamClient or RtspStreamClient. Since you don't know which protocol you will use until startStream you can't return the right class. This is the only problem I can see.

We must keep old classes for backward compatibility (RtmpCamera1, RtspCamera1, SrtCamera1, etc. Remove ConnectCheckers could be fine) but for this case we can create a new class that contain all protocols and startStream only with the protocol that match with the url. Basically clone RtmpCamera1 (for example) and add RtspClient and SrtClient.

About ConnectChecker. We can create a generic one but keep in mind 2 requirements: 
- Keep rtsp, rtmp and srt usable without dependencies because other users maybe only need to use the protocol
- Use code usable for java and Kotlin so use an interface with default methods to avoid implements other methods like [here](https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/backgroundexample/ConnectCheckerRtp.kt) is not a solution because it is not usable in java. Maybe we can solve it creating a common module and add it as dependency in all protocols.

If you have a better idea. Let me know it and we can find the best solution.

Also, we should close this issue and open a new one since it is not related with the original case

**Comment by Ernovation** [comment]
Hi Pedro,

I will see what I can do and close this issue.

Regards,
Erik.

**Comment by pedroSG94** [comment]
Hello,

I did a branch for this case:
https://github.com/pedroSG94/RootEncoder/pull/1323

For now, I moved ConnectChecker to a new module. With this we can create the new class that include all protocol without implement all ConnectCheckers.
