### ISSUE TITLE
Display landscape video in portrait mode

### ISSUE THREAD

**Issue by r-nov** [pedroSG94/RootEncoder#1322]
Hello @pedroSG94 
Thank you very much for this library! 
Currently I facing a problem with streaming landscape video with phone in portrait mode, may I ask for your help?

My parameters:
- **Video:** any resolution supported by camera, 16:9 and 4:3 ratio.
- **App:** RtspCamera2 + OpenGLView (OpenGL is only option in my case so I can't use surface/texture to fix this problem). Basically it's background example with RtspCamera2. App always in portrait mode only.

I would like to stream landscape orientated video from phone camera when my app is in portrait mode, but I can't find the way to set camera rotation properly.
For example (I will use startPreview() as example):
**camera?.startPreview("0", 1920, 1080, fps, 90)** - video in portrait mode (9:16, not 16:9), how can I change video orientation (make it 16:9) in this case?
I tried RotationFilterRender and glInterface.setRotation(), but no luck.

To make my question clear I'll add image with behaviour I would like to achieve.
![image](https://github.com/pedroSG94/RootEncoder/assets/131220484/f4609246-5900-4148-a098-662570c06aed)

Thank you in advance!

**Comment by pedroSG94** [comment]
Hello,

You have a similar case using this example but in this case it is starting from landscape resolution:
https://github.com/pedroSG94/RootEncoder/tree/master/app/src/main/java/com/pedro/streamer/rotation

I added a commit to support your case because before that only landscape original size was allowed.
You only need to compile my app example with last commit and modify this line:
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/rotation/StreamService.kt#L106
To:
```kotlin
prepared = rtmpCamera?.prepareVideo(640, 480, 1200 * 1000, rotation = 90) ?: false &&
```
This way when you have the device in portrait and you rotate your device to landscape while streaming you  will see the second image in player side

**Comment by r-nov** [comment]
Thank you very much for your answer! Really appreciate your support with all issues and questions. 

I'm sorry but I will be able to check it all and answer next week because of vacation.

**Comment by r-nov** [comment]
Sorry for the wait.

I tried your approach but unfortunately still no luck.

After this steps video is still portrait only and I couldn't change rotation correctly without rotating device. I tried different resolutions and rotation values, but couldn't rotate video properly to display it horizontally while device in portrait mode.
Yes, it works if I rotate device to landscape orientation, but in my case I have to use device in portrait mode only and can't rotate device or change app rotation to landscape to change video rotation.

Thank you.

**Comment by pedroSG94** [comment]
Hello,

Now, I can understand your case but it is not possible without deform the image.
The camera image in portrait is a vertical resolution so if you force it to landscape. You have 2 options:

- Deform the image (basically resize to landscape).
- Rotate the image resulting in an image with wrong orientation.

Just to explain. Using a resolution of 640x480 in vertical (so it is 480x640 in portrait and 640x480 in landscape):
First image with default scale of the library to avoid deform image:
![Screenshot_20231106-093428](https://github.com/pedroSG94/RootEncoder/assets/17556876/919046a1-3ea3-469c-bc1c-413aea763adb)


Second image removing keepAspectRatio and aspectRatioMode in XML to adapt image to device screen deforming image:


![Screenshot_20231106-093521](https://github.com/pedroSG94/RootEncoder/assets/17556876/8d3fdb7b-32b4-41f8-9eb9-91eac5879888)


Third image as you suggested with horizontal resolution in vertical device orientation deforming image but in this case deformed in width (same as second image but using a custom width/height of OpenGlView, in this case full width and 480dp height):


![Screenshot_20231106-093639](https://github.com/pedroSG94/RootEncoder/assets/17556876/9d6323a0-8991-42de-ae2a-3d815fa871ec)

This is the result because the original scale image is the first one and you are scaling it to fill a wrong resolution. But maybe I miss understand again and you mean this:
![Screenshot_20231106-094550](https://github.com/pedroSG94/RootEncoder/assets/17556876/571df04a-7462-475c-92dd-4cc7d36b9fb3)

As you can see you have black borders in the horizontal in this case. This is the same configuration than the first image but with OpenGlView using a custom size instead of full screen size. In this case full width and 480dp height

**Comment by r-nov** [comment]
Thank you for detail explanation with examples. Now I got it.
Just one more question. Maybe it is possible to crop image to fit it horizontally without deforming? It will work in my case so maybe there's a way to do this.
Something like this. 
![image](https://github.com/pedroSG94/RootEncoder/assets/131220484/9946f43b-32b2-4bfd-9840-9b795476de9f)
Thank you again.

**Comment by pedroSG94** [comment]
Yes, but the image will be rotated 90º in your case so the orientation will be wrong

**Comment by r-nov** [comment]
Thank you. Now I see. Also spent some time to understand flow inside library better and now I got it. 
Maybe you could help me with one more question? Seems like I have no other options but use libyuv to transform image (it's not a problem to implement it, but seems like you already implemented useful functions in encoder/utils/yuv/YUVUtil.java :))
In my mind I will use _onImageAvailable_ from _OnImageAvailableListener_ of _ImageReader_ and do all my frame transformation stuff there. My questions is will I be able to use OpenGLView with the ImageReader? 
Thank you.

**Comment by pedroSG94** [comment]
Hello,

OnImageAvailableListener provide a byte array in YUV/RGB formats but OpenGlView need a surface to render so It is not compatible.
I'm not sure what do you need but, If you are using camera2 you can Use RtmpCamera2 with OpenGlView and use addImageListener that provide you access to an OnImageAvailableListener

**Comment by r-nov** [comment]
RtmpCamera2 will be completely fine for me, so I will try this approach.
If there's some examples or notes regarding RtmpCamera2/OpenGlView/addImageListener usage I would be glad to check it.
Thank you for your anwers, advices and support.

**Comment by pedroSG94** [comment]
Hello,

You can use OpenGl RTMP example. You only need change RtmpCamera1 to RtmpCamera2 and add image callback like this:
```java
//this line provide an Image with the size of the actual stream/preview size. if you want a different resolution you can use addImageListener(int width, int height, int format, int maxImages, Camera2ApiManager.ImageCallback listener)
rtmpCamera2.addImageListener(ImageFormat.YUV_420_888, 1, new Camera2ApiManager.ImageCallback() {
      @Override
      public void onImageAvailable(Image image) {
        //image received here
      }
    });
```

**Comment by r-nov** [comment]
@pedroSG94 I fixed my issue using simple matrix operations. Thank you very much for clear explanations, it helped me a lot to understand whats going on.
I set rotation to 0 degrees and then just flipped matrix and scaled Y axis to correct value, thats all :)
