### ISSUE TITLE
Problem to using library to streaming RTMP 

### ISSUE THREAD

**Issue by peyrovi98** [pedroSG94/RootEncoder#1331]
I want to stream on a Java server, But the stream does not start.
It is done with OBS software on the server, But I can't stream with your library.
Server I use:
[https://github.com/YuboLong/MyLive](url)

**Comment by pedroSG94** [comment]
Hello,

Can you provide me a jar compiled? I have errors compiling that server

**Comment by peyrovi98** [comment]
Hello
Thank you for your response.
Sure.
[Uploading mylive-serv.zip…]()

**Comment by pedroSG94** [comment]
I think it is not properly uploaded. I can't download it

**Comment by peyrovi98** [comment]
Oh, yes. Sorry about that...
[https://www.mediafire.com/file/voiy2xbmjl1efwn/myLive.rar/file](url)

**Comment by pedroSG94** [comment]
Hello,

I detected the problem but it is a bug in server side.
The server crash parsing this line:
https://github.com/pedroSG94/RootEncoder/blob/master/rtmp/src/main/java/com/pedro/rtmp/rtmp/CommandsManagerAmf0.kt#L44
You can remove it but even with that the audio result using ffplay as player is bad (also a bug in the server) and VLC is not working.
Even using ffmpeg as encoder to test it is not working fine
I really recommend you use other server because this player seem abandoned (2 year without updates) so I think the owner never will fix it.
I think this is a good alternative:
https://github.com/bluenviron/mediamtx

**Comment by peyrovi98** [comment]
Hello. Thank you for taking the time to help me.
Currently, I am trying to use a Java server. The server is supposed to run on a mobile phone.
Is it possible to use this library in an Android project?

**Comment by pedroSG94** [comment]
Hello,

Yes, my library is basically oriented to Android devices so you can use it but I haven't server features.
Of course you can use that server in an Android project (you only need move all classes to an Android project) but you will need to fix all errors by yourself.

**Comment by peyrovi98** [comment]
Hello again,

I checked the Java server source using your guide, I found that in this line if I change the Integer to Double, the server crash problem is solved:
https://github.com/YuboLong/MyLive/blob/6f9a65cb26135fed60edc8dc1e8c734421318f42/src/main/java/com/longyb/mylive/server/handlers/RtmpMessageHandler.java#L280

old:
`Integer clientRequestEncode = (Integer) ((Map) msg.getCommand().get(2)).get("objectEncoding");`
new:
`Double clientRequestEncode = (Double) ((Map<?, ?>) msg.getCommand().get(2)).get("objectEncoding");`

Thank you for your help and quick response. (❤ ω ❤)
