### ISSUE TITLE
How to apply new resolution when camera switched

### ISSUE THREAD

**Issue by TayfunCesur** [pedroSG94/RootEncoder#1334]
Hello Pedro, I've been playing around for some time.  Amazing work you did, I really appreciate that. I have a question which I tried for some time but couldn't figure out. Thanks in advance for any guidance.

**Context**: OpenGlRtspActivity.java
**Device**: Pixel 3a
**Version**: Latest

I want to use higher and best resolution which is supported by the device. Here the steps I followed,
- Used RtspCamera2 instead of RtspCamera1
- I have a function which gives me the best possible resolution according to resolution I want.
   `Size optimalResolution = getOptimalPreviewSize(List.of(cameraManager.getCameraResolutions(cameraManager.getCameraFacing())), 4000, 2100);`
If I use it like this, it gives me `3840x2160`
- I provided these values with `startPreview` and `prepareVideo` everything worked as expected. 

### Question: How to apply this when camera switched?

I calculated the optimal size when camera switched.  I have `2592x1944` for front camera. Now, how can I apply this change to preview and the stream without stop/start preview?(I prefer to do it while streaming)  I couldn't find a way to apply the new size to the surface. So the preview and stream is distorted currently. Once set, it always uses the first set resolution which may not be the best for switched camera.

I'm attaching my local changes as a patch, feel free to take a look.
[Playground.patch](https://github.com/pedroSG94/RootEncoder/files/13305001/Playground.patch)

Best,

**Comment by pedroSG94** [comment]
Hello,

This library is designed to work with the same resolution with back and front camera while you are recording/streaming. If you want change that resolution you need to stop stream and preview to change it (by default). 
The reason is avoid problems with different aspect ratios and resolutions exactly as you commented.

For your case, I recommend you change that front resolution to one with the same aspect ratio like 2560x1440 to avoid distortion

**Comment by TayfunCesur** [comment]
Thank you so much Pedro, I love your work.
