### ISSUE TITLE
rtspFromFile always show dropping frame that's going backward in time

### ISSUE THREAD

**Issue by lchy12345** [pedroSG94/RootEncoder#1354]
Hi pedro,

when i am using a video only file for streaming rtsp, it will always shows "GraphicBufferSource: Dropping frame that's going backward in time" in between "BaseRtpSocket: TCP wrote packet: Video, size: xxx".

I can see that from VLC player for playing this stream, there are many video frame dropped.

if i use video with audio file for streaming rtsp, it seems to work well without any error message.

i am writing the code in this way, may i know if i did anything wrong:

rtspFromFile.setOnlyVideo(true)
rtspFromFile.setLoopMode(true)
rtspFromFile.preparevideo(path)
rtspFromFile.startStream(rtspServer)

Thank you very much.

**Comment by lchy12345** [comment]
i have tried using the lastest master code, but the problem still there

**Comment by pedroSG94** [comment]
Share me a video to reproduce the problem and let me know media server name/version used

**Comment by lchy12345** [comment]
i can reproduce the problem using this video

https://github.com/pedroSG94/RootEncoder/assets/89956234/25ab560b-4dfb-4308-8c41-fbb2679ebfd2


I am not sure what you mean by media server name/version. I am using this https://github.com/bluenviron/mediamtx as my rtsp server.

Thank you very much.

**Comment by pedroSG94** [comment]
> I am not sure what you mean by media server name/version

I mean the server (in your case mediamtx) and the version that could be the last, 1.3.1.
If you are using other version, let me know it. I already downloaded the video and I will start tests as soon as I can.

Keep in mind that I will test with the master branch with RTSPFromFile example without modifications (I will only add onlyVideo and loopmode methods). If you need any modification or tip to reproduce it. Let me know it.

I will report progress here

**Comment by pedroSG94** [comment]
Hello,

After multiple tests. I can reproduce your warning log but It is not related with lose frames sometimes. I can reproduce it with others videos without lose frames so the log is not relevant.
I think that it is because the video is always black with a really low bitrate and since the frames lost are really low and only happens with full black video (around 1 frames each 2 second in my case) I don't need to do anything about it.

I will mark this issue as invalid. Thank you for your report.
