### ISSUE TITLE
Fast moving objects are blurred

### ISSUE THREAD

**Issue by artemiskot** [pedroSG94/RootEncoder#1373]
Hi Pedro! Currently, I am developing an app to capture small, fast-moving objects in each frame (for example, the number on a fast-moving car) to teach our neural network to detect exact literals and numbers. We need the car's plate to be clear in each frame received, but in some of them, we receive videos of not very good quality. We've adapted your background activity, use a 1920x1080 stream at 60 fps, and an 8000 bitrate. Also, we use settings like ISO, exposure, focus distance, and zoom for better image quality in any type of area, but we're still not really satisfied with the image quality. We've set the iKeyFrame interval to 0 to prevent high compression of the image, but it didn't help greatly.

What can we change/implement to receive perfect video? Our internet connection is stable in our tests(so thats not the issue). We've used rtsp stream from your backround example as a sample. @pedroSG94

**Comment by pedroSG94** [comment]
Hello,

First of all, since you are using H264 or H265 (I recommend you test with H265 that should get a better quality with the same bitrate) you will lose quality no matter what you do.

Use raw video with, for example, a yuv nv21 (a format that you can get from the camera API in Android) will use a high bandwidth. We are talking that if you want raw video with 1920x1080 60fps this is:
1920 * 1080 * 3 / 2 * 60 = 186624000 bytes per second (186,62 MBps). So we can discard this.
It is possible using a RTP packet with RTSP but I don't know a server that support it and I think it is not worth. I link you the RFC anyway:
https://datatracker.ietf.org/doc/html/rfc4175

Even with that remember that you need a device designed to get a good quality with moving objects or you will get blur images. Somes devices use cameras close to a slow motion (high rate fps) or AI to process the image for that reason.

Anyway you can try this to improve the quality:
- Use H265 to reduce the bitrate necessary to get the same quality so you can use the same bitrate and the quality should be a bit better
- Increase fps if possible to reduce the blur
- Use a higher resolution like 4k (this also need increase the bitrate to get a good quality)
- Play a bit with encoder parameters. For example using H265 you have [constant quality mode](https://developer.android.com/reference/android/media/MediaCodecInfo.EncoderCapabilities#BITRATE_MODE_CQ) in few encoders. You can change the value here (remember adapt the conditional or remove it):
https://github.com/pedroSG94/RootEncoder/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L140
Also, you can download an app like this to check all parameters allowed by your encoder and test any interested parameter:
https://play.google.com/store/apps/details?id=com.parseus.codecinfo&hl=en&gl=US
After install the app you will detect that you have more than one encoder for h264 or h265 so you can modify the library a bit to test all encoder just in case but by default the library use the hardware encoder that usually is better
