### ISSUE TITLE
getBitRate() with GenericStream, StreamBase?

### ISSUE THREAD

**Issue by kenle** [pedroSG94/RootEncoder#1417]
Hi @pedroSG94 ,

In order to implement Adaptive Video Bitrate example using GenericStream (StreamBase), would I need public read access to videoEncoder in order to get the max bitrate with "getBitRate()", or maybe a "getBitRate()" convenience function within StreamBase?

https://github.com/pedroSG94/RootEncoder/blob/942212a0458ba8b3ca45864d6962a02905fc86cb/library/src/main/java/com/pedro/library/base/StreamBase.kt#L73C1-L74C1

https://github.com/pedroSG94/RootEncoder/wiki/Adaptative-video-bitrate

Thank you,
-Ken

**Comment by pedroSG94** [comment]
Hello,

Yes, you are right. The example is a bit outdated. 
I haven't that method in StreamBase because video bitrate is a necessary parameter for prepareVideo (you have a prepareVideo method without parameters using Camera1Base for example so it is necessary to know the default value), you can use the value set to prepareVideo method because getBitrate is only a getter of that value. So in Rotation example you can do it like this:
```kotlin
  private var bitrateAdapter: BitrateAdapter? = null

  override fun onConnectionSuccess() {
    toast("Connected")
    bitrateAdapter = BitrateAdapter { bitrate -> genericStream.setVideoBitrateOnFly(bitrate) }
    bitrateAdapter?.setMaxBitrate(vBitrate)
  }
  
  override fun onNewBitrate(bitrate: Long) {
    bitrateAdapter?.adaptBitrate(bitrate)
  }

```
I'm going to update the code example in the wiki.

**Comment by kenle** [comment]
Ok, noted @pedroSG94 .  Thank you very much!

**Comment by cryinrain69** [comment]
Hi @pedroSG94 
I have set `maxBitrate` as follows:
```kotlin
videoBitrate = 8000 * 1000
audioBitrate= 128 * 1000
bitrateAdapter = BitrateAdapter {
 genericStream.setVideoBitrateOnFly(it)
}.apply {
 setMaxBitrate(videoBitrate + audioBitrate)
}
```

But the bitrate I get (in `onNewBitrate`) is sometimes much higher than the `maxBitrate` I initially set (as in the image below):

![Image](https://github.com/user-attachments/assets/152b14ba-10d7-4dde-8dac-a406300cd9b6)

**Comment by pedroSG94** [comment]
Hello,

If you are using this:
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/rotation/CameraFragment.kt#L80
Remove the line because this line modify the bitrate to avoid receive high spikes, an spikes each x seconds is normal because the video encoder generate a keyframe each x seconds (value of iFrameInterval) which is higher than normal frames.

The value of setMaxBitrate is used to mark a value where the adaptative bitrate start to reduce the bitrate if the bitrate reported is higher than that value but the you can have higher values so it is not necessary an error.
