### ISSUE TITLE
Multicast

### ISSUE THREAD

**Issue by brian7704** [pedroSG94/RootEncoder#1420]
Does RootEncoder support UDP multicast?

**Comment by pedroSG94** [comment]
Hello,

If you want stream using UDP you can use RTSP with UDP or SRT.
If you want request implement other protocol. Please, share me documentation about the protocol including codecs supported if possible.

**Comment by pedroSG94** [comment]
The idea is support send mpeg-ts over udp multicast IP?

**Comment by brian7704** [comment]
> The idea is support send mpeg-ts over udp multicast IP?

Yes for example to 239.1.1.1:1234.

**Comment by brian7704** [comment]
I found this command in MediaMTX's README about how to create a multicast MPEG-TS stream with FFMPEG.

`ffmpeg -re -f lavfi -i testsrc=size=1280x720:rate=30 \ -pix_fmt yuv420p -c:v libx264 -preset ultrafast -b:v 600k \ -f mpegts udp://238.0.0.1:1234?pkt_size=1316`

**Comment by pedroSG94** [comment]
Hello,

I did a branch for it. It is a beta for now and I have more work to do but maybe this could work for you:
https://github.com/pedroSG94/RootEncoder/pull/1423

Just compile the branch and open rotation example. Then write your url, for example:
udp://239.0.0.1:1234
This should start multicast UDP stream. You can reproduce it using ffplay with command:
```
ffplay udp://239.0.0.1:1234
```
A server is not required for this.

**Comment by brian7704** [comment]
Thank you! I'm trying it now and I'll let you know how it works.

**Comment by brian7704** [comment]
Hi Pedro, it seems to work well using GenericCamera2. My only question is about audio codecs. I see in the README you said that UDP can support OPUS but GenericCamera2 does not support OPUS. I tried using RtspCamera2 instead but it said that my url udp://239.1.1.1:1234 was not the correct format for an RTSP stream. Should I use GenericCamera2 or another one?

Thanks again for your hard work!

**Comment by pedroSG94** [comment]
Yes, UDP should support OPUS but I need add a class named UdpCamera2 for it (and variants). 

The idea with Generic classes is only support commons codecs for all protocols in order to be able to stream protocol in the startStream method. If you want use a codec not supported in all protocols (OPUS is not supported in RTMP) you need use the specific class for that protocol.
It is not finished yet, It is only a first version. I have plan to add that classes and test more. 
Let me know if you find any error.

Anyway you can create UdpCamera2 class easy. You can copy SrtCamera2 class and replace SrtClient to UdpClient and SrtStreamClient to UdpStreamClient

**Comment by pedroSG94** [comment]
I just added that classes. Update the branch and you have UdpCamera2 class

**Comment by brian7704** [comment]
Thank you! I tested UdpCamera2 and it works as expected with all audio codecs. I was able to view the stream in VLC using this address `udp://@239.1.1.1:1234`

**Comment by pedroSG94** [comment]
Closed as finished. You can open other issue if you have problems
