### ISSUE TITLE
How to record screen on android

### ISSUE THREAD

**Issue by MinhMinh8722** [pedroSG94/RootEncoder#1508]
Can you show me where the code for recording the screen and saving the file into local storage?
Thanks!!! 🙏

**Comment by pedroSG94** [comment]
Hello,


If you want record the screen you can use this example:
https://github.com/pedroSG94/RootEncoder/tree/master/app/src/main/java/com/pedro/streamer/screen

If you want record instead of stream you can replace isStreaming to isRecording, startStream to startRecord and stopStream to stopRecord.

isStreaming:
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/screen/ScreenService.kt#L112
To:
```kotlin
return genericStream.isRecording
```
startRecord:
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/screen/ScreenService.kt#L155
To:
```kotlin
    if (!genericStream.isRecording) genericStream.startRecord(filePath)
```
And stop record:
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/screen/ScreenService.kt#L119
To:
```kotlin
  fun stopStream() {
    if (genericStream.isRecording) {
      genericStream.stopRecord()
      notificationManager?.cancel(notifyId)
    }
  }
```

In ScreenActivity you will need replace the stream url provided in the startRecord to a valid file path

**Comment by MinhMinh8722** [comment]
Thanks for your answer. And can I draw a watermark on surfaceview?

**Comment by MinhMinh8722** [comment]
Thank @pedroSG94 .
