### ISSUE TITLE
Set SRT latency

### ISSUE THREAD

**Issue by perotom** [pedroSG94/RootEncoder#1515]
I didn't find any information about setting SRT latency. Is the SRTSender's `cacheSize` the latency?
https://github.com/pedroSG94/RootEncoder/blob/b625dd7730b69cca5a2a50cc9066b3e864281bc5/srt/src/main/java/com/pedro/srt/srt/SrtSender.kt#L73

If yes, in which unit and I think it would be awesome to let people set it manually (in some use-cases we even use this latency to synchronise different cameras.

**Comment by pedroSG94** [comment]
Hello,

No it isn't the latency.
The value is used to store video/audio packets if you have internet problems (you have no enought bandwidth to send it in realtime).
This could produce latency if you connection is bad but mainly it is used to solve a quick internet drop and to calculate [Adaptative video bitrate](https://github.com/pedroSG94/RootEncoder/wiki/Adaptative-video-bitrate) depend of the size filled.

Actually this library should produce about 0.1-0.3s of delay (I calculated it and the most of the time is in the video/audio encoder in the Android MediaCodec class) and you can't reduce it in this side.
The only way to reduce the delay is in server/player side (mostly in player side because the player allways need a buffer to work so it isn't realtime)

**Comment by perotom** [comment]
Ahh ok I see. Thank you very much for the information! This library really is great 👍🏼
