### ISSUE TITLE
Bitrate on screen not matching streamed bitrate

### ISSUE THREAD

**Issue by perotom** [pedroSG94/RootEncoder#1517]
**Describe the bug**
I was testing out the `genericStream.setVideoBitrateOnFly(videoBitrate)` method and came to some strange behaviour. I am streaming via SRT and noticed the bitrate which is reported via `onNewBitrate` is not matching the one received by the server.

**To Reproduce**
1. Change bitrate during streaming

**Expected behavior**
Bitrate should be matching approx. set bitrate.

**Screenshots**
I tried two cases: Changing bitrate from 2mbit to 8mbit and the other way round. In both cases the selected bitrate is not even after 1min of streaming:

Changed from 8mbit to 2mbit at 11:27:05
![8mbit-2mbit](https://github.com/pedroSG94/RootEncoder/assets/3322872/f5e0bc88-32ae-4228-bd24-1a6f8d0b63ab)
Changed from 2mbit to 8mbit at 11:56:00
![2mbit-8mbit](https://github.com/pedroSG94/RootEncoder/assets/3322872/5b4bb075-4139-4024-b2c7-48d7c6afe4fc)

Furthermore, I regularly (every 5-10 sec) see a jump in double or more the bitrate for 1 sec. Following example for a set bitrate of 8mbit: `8, 8, 8, 16, 8, 8, 8, 16, 8, 16, 8, 8, 8`.

**Smartphone (please complete the following information):**
 - Library version 2.4.5
 - OS: Android12

**Comment by pedroSG94** [comment]
Hello,

bitrate of onNewBitrate callback is calculated with the number of bytes send by the sockets. This include packaging size (in this case mpegts)
So that value is the bytes that you send but could be different in server side if you lose packets

How did you get that screenshot? 
Can you tell me the media server used?
Did you test with a local server to discard that you lose packets?

**Comment by perotom** [comment]
Thanks for the information.

The screenshots were taken from a live transcoder software https://callaba.io. And I did another test with "drop" metric:

![Screenshot 2024-07-04 at 15 49 13](https://github.com/pedroSG94/RootEncoder/assets/3322872/f7181861-6a6b-450b-af88-0ecbf0e9705f)
![Screenshot 2024-07-04 at 15 50 43](https://github.com/pedroSG94/RootEncoder/assets/3322872/f2575724-46aa-4017-8992-3cc6f7889ded)


I didn't find a quick way to setup an SRT server on my local machine to do local testing (do you know any tool?). I just tried it with RTMP locally and remotely and it worked fine.

Either the transcoder software displays something wrong (somehow I trust it because when I restart the stream on Android, the correct bitrate is shown) or there is a problem when using SRT.

This strange jumps in bitrate also only happens when using SRT. With RTMP everything works fine.

https://github.com/pedroSG94/RootEncoder/assets/3322872/9f571d27-0360-4330-bbfd-10c3114dfce5

In the transcoder software I don't see any spikes like the Android reports. I am using just H264 for all tests. Any ideas?

**Comment by pedroSG94** [comment]
You can use this media server in local:
https://github.com/bluenviron/mediamtx

About that spikes in Android using SRT. This is maybe related with the way this library create mpegts packets that generate and send psi packets each video keyframe. This could be the cause of this spikes in Android side. Anyway, I will check it to make sure that it is not a bug.

If you can't see that values in callaba.io maybe this is because that metric is using an average of bitrate from the start. In my case I show the exact bitrate in that second, not an average

**Comment by pedroSG94** [comment]
> I see, so as the keyframes are every 2nd sec, that's why I sometimes see 3x the value?

Yes, the default value is 2 second but you can configure it as you want (iFrameInterval). recommended values 1-5:
https://github.com/pedroSG94/RootEncoder/blob/master/library/src/main/java/com/pedro/library/base/StreamBase.kt#L103

**Comment by perotom** [comment]
Ok, as far as I understood it, the adaptive bitrate is also depending on the correct value of `onNewBitrate`. I created a pr with a proposed moving average which solves this issue.
