### ISSUE TITLE
How to correctly set the properties of a video

### ISSUE THREAD

**Issue by Moyout** [pedroSG94/RootEncoder#1541]
```
genericStream.prepareVideo(640, 480, vBitrate, 30)

width: 640,
height: 480
vBitrate:  1200 * 1000
fps: 30
```
These values make the video stream look very unclear.
How can I set attributes correctly？Or know some properties of the device .

**Comment by pedroSG94** [comment]
What do you mean with unclear? pixelated? low resolution?
Did you tried with 1080p?

width: 1920,
height: 1080
vBitrate:  8000 * 1000
fps: 30

**Comment by Moyout** [comment]
> 你说不清楚是什么意思？像素化？低分辨率？你试过1080p吗？
> 
> 宽度：1920，高度：1080vBitrate：8000 * 1000fps：30

Never tried.
Your example includes these attributes, which are directly used for testing.

😆

**Comment by Moyout** [comment]
> 你说不清楚是什么意思？像素化？低分辨率？你试过1080p吗？
> 
> 宽度：1920，高度：1080vBitrate：8000 * 1000fps：30

Sometimes setting other values doesn't work

**Comment by Moyout** [comment]
> 你说不清楚是什么意思？像素化？低分辨率？你试过1080p吗？
> 
> 宽度：1920，高度：1080vBitrate：8000 * 1000fps：30

So I want to know the relationship between these attributes,  how to correctly set the values of these attributes

**Comment by pedroSG94** [comment]
That values depend of your needs.
480p is low resolution and supported by all devices so it is used by default in the example because all devices should works fine with that. This is also to keep the example simple and avoid create a selector.
After that, you need adapt it as you want. Depend of the quality needed you can use one resolution/bitrate or other. You have a table of recommended bitrates for resolution by Youtube (you can use it as guide in all platforms because the protocol used is the same RTMP):
https://support.google.com/youtube/answer/2853702?hl=en

I recommend you use 1080p for good quality, 720p medium quality and 480p low quality with that bitrates (higher bitrate require higher bandwidth).

**Comment by Moyout** [comment]
> 这些价值观取决于你的需求。480p是低分辨率的，所有设备都支持，因此在示例中默认使用它，因为所有设备都应该正常工作。这也是为了保持示例简单，避免创建选择器。在那之后，你需要随心所欲地调整它。根据所需的质量，您可以使用一个分辨率/比特率或其他。您有一个Youtube分辨率的推荐比特率表（您可以在所有平台中将其用作指南，因为使用的协议是相同的RTMP）： [https://support.google.com/youtube/answer/2853702？hl=en](https://support.google.com/youtube/answer/2853702?hl=en)
> 
> 我建议您使用1080p以获得高质量，720p中等质量和480p低质量与该比特率（更高的比特率需要更高的带宽）。

Thank you.
