### ISSUE TITLE
sps or pps is null when work with MediaProjection

### ISSUE THREAD

**Issue by Lyman92** [pedroSG94/RootEncoder#1547]
Hi @pedroSG94 
I copied  ScreenActivity And ScreenService from the master branch.
switch Kotlin to java.
I run my code on an Android TV
Any suggestion for me. Thanks!

**Comment by Lyman92** [comment]
Solved by foring software encoding.
`genericStream.forceCodecType(CodecUtil.CodecType.SOFTWARE, CodecUtil.CodecType.SOFTWARE);
prepared = genericStream.prepareVideo(width, height, vBitrate, rotation) &&  genericStream.prepareAudio(sampleRate, isStereo, aBitrate);`

**Comment by pedroSG94** [comment]
Hello,

If the demo is working and you code is not working fine. I can't tell you the reason without without check your code.
For now, my only suggestion without check the code is that you should make sure that you added this line:
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/screen/ScreenService.kt#L77
As you can read in the comment, this is important using mediaprojection because that api only render if you update the screen content. This line force the library to render in a constant interval no matter if the screen content change.

This could be related with your case because if you never update the screen, maybe you encoder never produce the sps or pps because need more frames to do it.

**Comment by Lyman92** [comment]
I did not realize the named parameters of kotlin
`genericStream.prepareVideo(width, height, vBitrate, rotation)`
should be
`genericStream.prepareVideo(width, height, vBitrate, 15, 2, rotation)`
