### ISSUE TITLE
The frame rate of local video streaming drops due to adding FilterRender

### ISSUE THREAD

**Issue by orzlenmo** [pedroSG94/RootEncoder#1554]
I have two phones, one is a Xiaomi 10 with a Snapdragon 865 processor, and the other is a generic brand with a Snapdragon 730 processor. I installed the same demo on both phones, streaming a local video file at 30 FPS. Then, I applied three SnowFilterRender filters on both devices. Gradually, the Xiaomi 10 maintained the 30 FPS, but on the generic phone with the Snapdragon 730, the frame rate dropped by 6 FPS with each additional SnowFilterRender filter. Eventually, the transmission frame rate was only a few frames. Does this have anything to do with the phone's processor?

**Comment by pedroSG94** [comment]
Hello,

Maybe this is related with the filter performance.
Anyway, I need more info about it to reproduce the case and try to solve it.

Let me know the video configuration (width and height) and the way you check fps. Did you check fps using fpslistener?
How many time do you need stream to notice that the fps is dropping toi few fps using only a filter?
Did you test with others filters to confirm that this only happens with snow filter?

**Comment by orzlenmo** [comment]
The video is 1080*1920 at 30fps. I have tried it and it has nothing to do with the filter. The only different variable is the mobile phone. One is a Snapdragon 865 processor and the other is a 730 processor. I also added fpslistener. The frame rate it outputs is the same as Xiaomi's stable video at 30fps. Snapdragon 730 does not add genericFromFile.glInterface.addFilter(SnowFilterRender()), and the output frame rate drops by about 5fps

**Comment by pedroSG94** [comment]
So, you tested with others filter and the problem persist. For example with GrayScaleFilterRender.
About drop 5fps each time you call addFilter. That is normal, you are basically adding more filters to the stream each time you call it. It is working like an internal ArrayList of filters:

**Comment by orzlenmo** [comment]
If the GPU of a Snapdragon 730 processor phone is not very powerful, could it also cause the frame rate to drop when processing OpenGL?

**Comment by pedroSG94** [comment]
Yes, could be a reason because if the GPU are 100% and something is not released properly the frame rate could be reduced. But I think that the main reason could be the temperature causing a thermal throttling.

Anyway, I need that other info I requested you to properly know the reason:
- Can you reproduce it using other filter? (GreayScaleFilterRender)
- Did you test using only a filter instead of add multiple filters that the fps keep constant? (Only call addFilter a time)
- Can you tell me the time needed to notice that fps is reduced while streaming using only 1 snow filter? (Only call addFilter a time).
- About the fps outputs, do you means fps returned by fps listener callback?

**Comment by pedroSG94** [comment]
Hello,

I updated the snow filter and now the performance with this filter is much better than before.
https://github.com/pedroSG94/RootEncoder/commit/65f72e7ccfdbcd29cf276f8239463328bc17a74d

**Comment by orzlenmo** [comment]
The performance of my 730 processor phone is too low, which causes the snowFilter to lag severely.
