### ISSUE TITLE
No audio with CameraUVC source 

### ISSUE THREAD

**Issue by osokindm** [pedroSG94/RootEncoder#1606]
Hello Pedro, I have a small problem:
when choosing UVC camera as source stream has no audio.
Smartphone mic, webcam mic, external usb mic - none of them works. 
Any other source, for example Camera 2,  works as expected

**Comment by osokindm** [comment]
Thank you, I indeed had just to change default value for MicrophoneSource class

**Comment by pedroSG94** [comment]
I think, he means this value:
https://github.com/pedroSG94/RootEncoder/blob/master/encoder/src/main/java/com/pedro/encoder/input/sources/audio/MicrophoneSource.kt#L33

**Comment by lemankk** [comment]
> I think, he means this value: https://github.com/pedroSG94/RootEncoder/blob/master/encoder/src/main/java/com/pedro/encoder/input/sources/audio/MicrophoneSource.kt#L33

Hi @pedroSG94  i tried switch different audio source type to this value, but none of them are able to receive audio from hdmi. 

I did also test the capture card device with CameraFi app and it works as expected for having sound feed from external sony camera. 
Is there something i missed or i need to change other source instead of using MicrophoneAudio class?

**Comment by pedroSG94** [comment]
I'm not sure the way CameraFi receive audio from the camera and I have no way to test it because I haven't a USB camera with audio. I only have a webcam with only video.
You can also try using this method:
https://github.com/pedroSG94/RootEncoder/blob/master/encoder/src/main/java/com/pedro/encoder/input/sources/audio/MicrophoneSource.kt#L50
This is used normally to switch to bluetooth device but maybe works. Check this issue:
https://github.com/pedroSG94/RootEncoder/issues/1664
