### ISSUE TITLE
How to zoom in rtspcamera2?

### ISSUE THREAD

**Issue by Roseclear** [pedroSG94/RootEncoder#1663]
-How to zoom in rtspcamera2? or just switch to rtmp instead?
-What should I use?, RTMP or RTSP better?
-Thanks!

**Comment by Roseclear** [comment]
![ảnh](https://github.com/user-attachments/assets/2a1bce9e-9a3d-4e05-99ac-61044b1be248)
Hmm... MotionEvents?

**Comment by pedroSG94** [comment]
Hello,

For zoom you can use the method you shared if you want implement zoom using gestures or use zetZoom, getZoom and getZoomRange methods to set manually zoom values as you want.

About RTMP and RTSP. You can use anyone of that protocols, they are similar but RTSP support more codecs and allow use UDP sockets which should be better for latency.

About you configuration, I don't understand it. 
The configuration is provided in prepareVideo and prepareAudio methods
- setVideoBitrateOnFly is used to modify video bitrate while streaming/recording, this is normally used to avoid netowrk congestion in weak network enviroments 
- setLimitFpsOnFly is similar but it is not recommended because could produce problems in the quality because could modify the keyframe interval.

**Comment by Roseclear** [comment]
Thanks

**Comment by Roseclear** [comment]
Close this issuse pls:)
