### ISSUE TITLE
Processing Frames For object detection to stream results using SRT

### ISSUE THREAD

**Issue by MennoScholten** [pedroSG94/RootEncoder#1665]
Hi, I'm a student who is studying your API and i have some question about an implementation using your API

I would like to do some object detection on a video livestream and send the results (So a livestream video with bounding boxes) with SRT

For the object detection i will use TensorFlow-LITE. How can i extract such a videostream from your API, apply object detection, and send the stream through SRT to a remote server.
I sincerely hope that you could give me some advice/directions in which way i should impelent your API.

**Comment by pedroSG94** [comment]
Hello,

To send the detection to stream you can use AndroidViewFilterRender. You can create a XML, set it to the filter and modify that view in realtime.
About the detection, this depend of your detection object API, what do you need to work?

**Comment by pedroSG94** [comment]
Can you work with an [Image](https://developer.android.com/reference/android/media/Image.html) or a Bitmap directly?
You can try use Camera2Base (SrtCamera2) or StreamBase (SrtStream) and use addImageListener to capture Image object from the camera.

**Comment by AlexUrrutia** [comment]
```
rtmpCamera1.getGlInterface().takePhoto(new TakePhotoCallback() {
            @Override
            public void onTakePhoto(Bitmap bitmap) {
            //Do what you need to do here with the image
}
```

**Comment by pedroSG94** [comment]
Hello,

You don't need to work with openGl for it. Using AndroidViewFilterRender you only need make a view and update the view according with values received by your object detector.
For now, try to implement a code example of SRTCamera2, you can follow OldApiActivity example, replace GenericCamera1 to SRTCamera2 and replace AutoFitTextureView to OpenGlView, with that you are ready to add the AndroidViewFilterRender like this:
https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/utils/FilterMenu.kt#L99
Now, add the image listener to obtain frames from the camera using addImageListener method and use it to get object dectection in real time.
With that values you can modify the XML in real time to represent your object detection according with your values.

**Comment by pedroSG94** [comment]
Hello,

The latency depend of multiple things.
This library has latency but only the necessary to process frames. I'm not adding latency to the stream, normally the latency is in the player side because the player need a bit of cache to work.

In this library the latency should be around 0.1s-0.2s encoding (depend of the encoder this could be less) + the video / audio processing (OpenGl rendering, audio filters, etc) + protocol packetization + time to send the buffer (depend of network).
If you are using OldApi with camera2 the only difference with rotation example is the OpenGl rendering but should be really similar or even the same.
