### ISSUE TITLE
rtmp can't setting fps.

### ISSUE THREAD

**Issue by Ten-Wang** [pedroSG94/RootEncoder#915]
I have a request that I need set fps to 24.
And I tried it, but it still 30.
I tried old ver. until downgrade to 1.9.5, still have the same issue.

**Comment by pedroSG94** [comment]
Which mode and view are you using? Camera2 with OpenGlView should works.

**Comment by iamweiqian** [comment]
![IMAGE 2021-08-25 18:29:00](https://user-images.githubusercontent.com/12478838/130774673-c9a2d127-073c-452a-971f-101f50b42955.jpg)

I'm having the same issue as well, using Camera2
`rtmpCamera2.prepareVideo(1280, 720, 25, 1200 * 1024, 2, CameraHelper.getCameraOrientation(this)`

**Comment by pedroSG94** [comment]
Hello,

Can you try change this value?:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/blob/master/rtmp/src/main/java/com/pedro/rtmp/rtmp/CommandsManager.kt#L145

I think that you are setting 25fps correctly but medatada is wrong for this method.
I recommend you set fps to 10 in prepareVideo and you can check if it is working correctly because it isn't smooth and you can see the difference
