### ISSUE TITLE
Change stream/record image without changing preview

### ISSUE THREAD

**Issue by ggpaeg** [pedroSG94/RootEncoder#970]
You can use both without preview.
But this will change rotation of all (preview if you have it, video record and streamed video). Only change rotation of streamed video is not supported.

_Originally posted by @pedroSG94 in https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/707#issuecomment-713374230_

Changing streamed video without changing preview is now supported?

I'm using sensorManager and prepareVideo to set the sensor rotation, but I want to keep the preview unchanged, so I can keep it locked in portrait mode.

**Comment by pedroSG94** [comment]
I explained how to implement this feature here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/531#issuecomment-963531623
If you want use a service as declared here:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/531#issuecomment-964735702
No, It isn't possible because change glinterface is not supported as I declared in the first link (read last line of limitations).
For now, you have 3 options: Use the first use case (without service), develop it yourself or wait for the feature.
