### ISSUE TITLE
Quality of view after render using openGL significantly reduced

### ISSUE THREAD

**Issue by MTayyabSarfraz** [pedroSG94/RootEncoder#990]
I'm using **OpenGlRtmpActivity** and rendered a text view using **AndroidViewFilterRender** class.
After rendering the textView seems to be pixelated, stretched.
I've tried to enhance the bitmap quality while rendering it on canvas but can not enhance the quality of output.
Is there a way to render view objects without compromising the quality? or there is any limitation to it.

_i've attached the screen short ....the top left switch camera button is the same text view as at bottom ... but see the quality, size difference after render_

Secondly, I've and I'm sure thousands of others who have benefited from @pedroSG94  your work would be highly grateful for this open-source generous effort.
I on my and their behalf thank you and others who contributed �
![Screenshot_1637914794](https://user-images.githubusercontent.com/28774273/143549485-ca244c2e-e941-4e34-9bf1-20190d98dfc7.png)
�

**Comment by pedroSG94** [comment]
Hello,

This is normal, it is not a bug. To solve, you need to do the following things:
- **Aspect ratio:** In this case you need calculate a correct size of your view depend of your view size and stream size. code example:
```java
   //return view size adapted to stream resolution to fix aspectRatio
  private PointF calculateOriginalSize(float originalWidth, float originalHeight, float streamWidth, float streamHeight, boolean isPortrait) {
    //The stream size is reverted if you are in portrait due to rotation. Fix it
    float w = isPortrait ? streamHeight : streamWidth;
    float h = isPortrait ? streamWidth : streamHeight;
    PointF point = new PointF();
    //Calculate real view value with: originalSize * 100 / streamSize
    point.x = originalWidth * 100f / w;
    point.y = originalHeight * 100f / h;
    return point;
  }
```

To apply in OpenGl example:
```java
        AndroidViewFilterRender androidViewFilterRender = new AndroidViewFilterRender();
        View view = findViewById(R.id.switch_camera);
        androidViewFilterRender.setView(view);
        rtmpCamera1.getGlInterface().setFilter(androidViewFilterRender);

        float w = view.getWidth();
        float h = view.getHeight();
        //640x480 is the resolution of stream/preview using default values
        PointF p = calculateOriginalSize(w, h, 640, 480, true);
        androidViewFilterRender.setScale(p.x, p.y);
```


- **Quality:** It is related with stream/preview resolution because it is like you are doing a zoom to the view. Since, the original view is displayed in device screen resolution and you are doing a stream with lower resolution the quality decrease, to solve it, you only need increase preview and stream resolution using startPreview and prepareVideo methods with parameters. For example, to solve preview:
```java
rtmpCamera1.startPreview(1920, 1080);
```
Remember change resolution set to calculateOriginalSize method created

**Comment by MTayyabSarfraz** [comment]
@pedroSG94 thanks for the quick feedback!

I'm trying to absorb what you just said and working on it...
I've achieved some success by hard coding the values .. but want to make these calculations dynamic.
hope will get through soon!!

I'm just curious why these screen resolution calculations are not dynamically calculated based on the device and then preview and stream resolutions are set accordingly ...used for streaming...apart from that you have done awesome work ... or maybe it is there but I'm missing it.

**Comment by pedroSG94** [comment]
The resolution of stream can't be calculated on library side to avoid cap library features. For this reason, it is necessary let the user choose all possible parameters to handle all app requirements. startPreview and prepareVideo without parameters was created only for debug and example purpose

If you means scale of filter it is a design decision to force users set a scale according with their own requirements (maybe you want increase the size or distort it).
By default the filter is drawed using view canvas parameters. Since, the normal screen size today use 2:1 aspect ratio if you use a stream with 4:3 aspect ratio (640x480) it is distorted.
It is not worth handle all possible cases. Maybe add the above method to library as a static method is possible but I want let users play with scale and position methods to understand how it is working instead of get this symple facility.

Anyway, I think that I should document how is working the scale and position methods in filters.
