### ISSUE TITLE
USB Camera Support ?

### ISSUE THREAD

**Issue by everestcastnp** [pedroSG94/RootEncoder#991]
It's possible to use an external camera which is connected  via OTG USB , Any Idea plz.

**Comment by pedroSG94** [comment]
No, It is not support by this library.
I haven't USB cameras to test and this code must be developed on C++ because you can't access to it on java/kotlin code. Also, it is a big project due to different hardware and Android versions problems. For that reason I haven't plan to support it by default but you can implement it yourself. You can replace Camera2ApiManager or Camera1ApiManager class in Camera1Base or camera2Base class with your own implementation of OTG USB camera and use it.

**Comment by pedroSG94** [comment]
Already supported in this issue (3rd party implementation):
https://github.com/pedroSG94/RTSP-Server/issues/110
Closing as inactive.
